Cicd
kubeportal/kubeportal-integration pull request #1
Opened 2020-08-30 19:19 UTC by kat-hi

2020-08-30 19:37 UTC, kat-hi commented
@troeger please review... I've got some hints for discussion:
- ingress hostname
- FE CICD still happens in the frontend-repository. we could have both builds in one repo but afaik this would always trigger both builds even if only one repo is updated. 
- could you add the TEST section for kubeportal to the workflow? I am not sure with that.

2020-09-11 12:57 UTC, troeger commented on .github/workflows/main.yaml
> +      - name: Set up Python 3.5
At least Python 3.6 is needed

2020-09-11 13:00 UTC, troeger requested changes

2020-09-11 13:00 UTC, troeger commented on .github/workflows/main.yaml
> +          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements-dev.txt; fi
Please use requirements-prod.txt

2020-09-11 13:00 UTC, troeger commented on .github/workflows/main.yaml
> +        run: ./manage.py test --configuration=Development
This is correct

2020-09-11 13:00 UTC, troeger commented on .github/workflows/main.yaml
> +          python-version: '3.5'
At least Python 3.6 is needed.

2020-09-13 09:56 UTC, kat-hi commented
@troeger RUN unittest still fails. could you have a look?

2020-09-13 13:28 UTC, troeger commented
Please pull the latest fe-api here, it contains a fix for the failing single test. I was not able to do that:

shaw:kubeportal-integration ptroeger$ make pull-api
git subtree pull --prefix kubeportal-api https://github.com/kubeportal/kubeportal.git fe-api --squash
fatal: Konnte Remote-Referenz fe-api nicht finden.

2020-10-07 14:16 UTC, closed without merging